Fix bug with loop initial declaration
Fixes bug induced in commit e15e2a77bd41833aa8676d44992f2790d323d67e

Bug:
/home/users/pogodzinski/melissa/api/melissa_api.c:1349:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (field_data_t* field_data_ptr = field_data; field_data_ptr != NULL; field_data_ptr = field_data_ptr->next) {
     ^
/home/users/pogodzinski/melissa/api/melissa_api.c:1349:5: note: use option -std=c99 or -std=gnu99 to compile your code