Examples: fix path referencing source directory
Fix a typo in a path that made the Code_Saturne launch script look for
files in the source directory instead of the installation directory. The
typo was discovered on the Jean Zay supercomputer when Code_Saturne and
Melissa were built with Spack because Spack built the code in a
host-specific directory in `/tmp`.

Error message by `run-code-saturne.sh` (look for `spack-src`):
```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/use61mq/spack-stage/spack-stage-melissa-develop-yli5p2av2filu7dyxjgkw3dnbnyvm5ts/spack-src/examples/Code_Saturne/MESH'
```